title: Alina Kadrova
lang: ru
email: your-email@domain.com
author: Alina Kadrova
description: "Привет меня зовут Алина <span>🙋</span>, я занимаюсь html-версткой и веб-дизайном <span>🖥</span>: от макетов до кроссбраузерных приложений <span>📱</span> и сайтов. Вы можете написать мне на почту <span>✉️</span> <a href='mailto:kadrova.alina@gmail.com'>kadrova.alina@gmail.com</a>."

baseurl: ""
url: ""

collections:
  projects:
    layout: project
    output: true

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
