title: Your awesome title
email: your-email@domain.com
author: Test Title
description: Nam rutrum quam nec ipsum dictum molestie. Fusce feugiat a lectus aliquet. Pellentesque fringilla gravida felis ut eleifend. Duis bibendum justo sit amet varius porttitor.

baseurl: ""
url: ""

collections:
  projects:
    layout: project    
    output: true

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
