title: Kadrova Alina
email: your-email@domain.com
author: Alina Kadrova
description: "Привет меня зовут Алина, я занимаюсь веб-дизайном: от макетов до верстки кроссбраузерных приложений и сайтов. Вы можете написать мне на почту."

baseurl: ""
url: ""

collections:
  projects:
    layout: project
    output: true

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
